# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ☔ Bersih
email: email@email.com
description: Just Ordinary Jekyll Theme
phone_number: XXXX - XXXX
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

discus_identifier: disqus # Add your Disqus identifier
google_site_verification : "XXXXXXXXXXXXXXXXXXXXXX" # Add your Google Site Verification
google_analytics: "UA-XXXXXXX-X" # Add your GA Tracking Id
theme_color: "#007bff" # Meta theme-color

paginate: 6
paginate_path: page/:num/
permalink: post/:slug

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed

defaults:
  -
    scope: # Default Front Matter For Post
      path: "_posts"
    values:
      layout: "post"
      image : "/Bersih/assets/images/thumb.png" # Default Thumbnail
      author: "XXXXXX" # Default Author Name On Post
  -
    scope: # Default Front Matter For Global File
      path: ""
    values:
      author: "XXXXXX"  # Default Author Name On Global File

social:
  name: "XXXXXX"
  links:
    - https://github.com/XXXXXX
    - https://codepen.io/XXXXXX

exclude:
 - README.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
